/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;

import static org.junit.Assert.*;
import static quotes.App.*;

public class AppTest {
    @Test
    public void testConstructor(){
        Quotes quote = new Quotes("someone", "helllo");

        assertEquals( "someone", quote.getAuthor());
        assertEquals( "helllo", quote.getText());
    }

    @Test
    public void testQuotes() throws IOException {

        Quotes[] convertedArray=getAllQuotes();
        System.out.println(convertedArray.length);
        Quotes randomQuote=convertedArray[(int) (Math.random()*convertedArray.length)] ;
        System.out.println(randomQuote);
        assertNotNull(convertedArray);
    }


    @Test
    public void testAddQuote() throws IOException {
        String apiURL="http://ron-swanson-quotes.herokuapp.com/v2/quotes";
        Quotes[] convertedArray=getAllQuotes();

        Quotes randomQuote=convertedArray[(int) (Math.random()*convertedArray.length)] ;
        URL url = new URL(apiURL);
        String jsonData = getJsonFromAPI(url);
        Quotes formismaticQuote = getFormismaticQuoteAsObject(jsonData);
        addToJsonFile(formismaticQuote);
        Quotes[] test=getAllQuotes();
        System.out.println(formismaticQuote);
        System.out.println(test[test.length-1]);
        assertEquals("the new qute should be the last one have benn added",formismaticQuote.toString(),test[test.length-1].toString());

    }
}
